// OpenAI ChatGPT conversation export types
// Generated by quicktype, then hand-cleaned

export interface ChatGPTConversation {
  title: string;
  create_time: number;
  update_time: number;
  moderation_results: any[];
  plugin_ids: null;
  conversation_id: string;
  conversation_template_id: null;
  gizmo_id: null;
  gizmo_type: null;
  is_archived: boolean;
  is_starred: null;
  safe_urls: string[];
  blocked_urls: any[];
  default_model_slug: string;
  atlas_mode_enabled: null;
  conversation_origin: null;
  is_read_only: null;
  voice: null;
  async_status: null;
  disabled_tool_ids: any[];
  is_temporary_chat: boolean;
  is_do_not_remember: boolean;
  memory_scope: string;
  context_scopes: any[];
  sugar_item_id: null;
  sugar_item_visible: boolean;
  pinned_time: null;
  is_study_mode: boolean;
  owner: null;
  mapping: Record<string, MappingNode>;
  current_node: string;
}

export interface MappingNode {
  id: string;
  message: Message | null;
  parent: string | null;
  children: string[];
}

export interface Message {
  id: string;
  author: Author;
  create_time: number | null;
  update_time: number | null;
  content: Content;
  status: string;
  end_turn: boolean | null;
  weight: number;
  metadata: MessageMetadata;
  recipient: string;
  channel: string | null;
}

export interface Author {
  role: "system" | "user" | "assistant" | "tool";
  name: string | null;
  metadata: Record<string, unknown>;
}

/** Discriminated by content_type */
export type Content =
  | TextContent
  | ModelEditableContextContent
  | ReasoningRecapContent
  | ThoughtsContent;

export interface TextContent {
  content_type: "text";
  parts: string[];
}

export interface ModelEditableContextContent {
  content_type: "model_editable_context";
  model_set_context: string;
  repository: null;
  repo_summary: null;
  structured_context: null;
}

export interface ReasoningRecapContent {
  content_type: "reasoning_recap";
  content: string;
}

export interface ThoughtsContent {
  content_type: "thoughts";
  thoughts: any[];
  source_analysis_msg_id: string;
}

export interface MessageMetadata {
  // system message flags
  is_visually_hidden_from_conversation?: boolean;
  is_contextual_answers_system_message?: boolean;
  contextual_answers_message_type?: string;
  rebase_developer_message?: boolean;
  command?: string;
  // request tracking
  request_id?: string;
  message_type?: string;
  turn_exchange_id?: string;
  message_source?: null;
  parent_id?: string;
  // model info
  model_slug?: string;
  default_model_slug?: string;
  resolved_model_slug?: string;
  // reasoning
  reasoning_status?: string;
  reasoning_start_time?: number;
  reasoning_end_time?: number;
  is_thinking_preamble_message?: boolean;
  // finish
  finish_details?: FinishDetails;
  is_complete?: boolean;
  finished_duration_sec?: number;
  // content
  citations?: any[];
  content_references?: any[];
  code_blocks?: Record<string, CodeBlock>;
  search_result_groups?: any[];
  search_model_queries?: SearchModelQueries;
  story_events?: any[];
  safe_urls?: string[];
  // UI flags
  hide_inline_actions?: boolean;
  disable_turn_actions?: boolean;
  can_save: boolean;
  model_switcher_deny?: any[];
  dictation?: boolean;
  triggered_by_system_hint_suggestion?: boolean;
  // misc
  chime_version?: number;
  permissions?: Permission[];
  skip_reasoning_title?: string;
  classifier_response?: string;
}

export interface CodeBlock {
  id: string;
  edited: boolean;
  previewable: boolean;
  preview_language: null;
}

export interface FinishDetails {
  type: string;
  stop_tokens: number[];
}

export interface SearchModelQueries {
  type: string;
  queries: string[];
}

export interface Permission {
  type: string;
  status: string;
  notification_channel_id: string;
  notification_channel_name: string;
  notification_priority: number;
}
