// OpenAI ChatGPT conversation export types
// Generated by quicktype, then hand-cleaned

export interface ChatGPTConversation {
  title: string;
  create_time: number;
  update_time: number;
  conversation_id: string;
  default_model_slug: string;
  is_temporary_chat: boolean;
  mapping: Record<string, MappingNode>;
  current_node: string;
}

export interface MappingNode {
  id: string;
  message: Message | null;
  parent: string | null;
  children: string[];
}

export interface Message {
  id: string;
  author: Author;
  create_time: number | null;
  update_time: number | null;
  content: Content;
  status: string;
  end_turn: boolean | null;
  weight: number;
  metadata: MessageMetadata;
  recipient: string;
  channel: string | null;
}

export interface Author {
  role: "system" | "user" | "assistant" | "tool";
  name: string | null;
  metadata: Record<string, unknown>;
}

/** Discriminated by content_type */
export type Content =
  | TextContent
  | ModelEditableContextContent
  | ReasoningRecapContent
  | ThoughtsContent;

export interface TextContent {
  content_type: "text";
  parts: string[];
}

export interface ModelEditableContextContent {
  content_type: "model_editable_context";
  model_set_context: string;
  repository: null;
  repo_summary: null;
  structured_context: null;
}

export interface ReasoningRecapContent {
  content_type: "reasoning_recap";
  content: string;
}

export interface ThoughtsContent {
  content_type: "thoughts";
  thoughts: any[];
  source_analysis_msg_id: string;
}

export interface MessageMetadata {
  is_visually_hidden_from_conversation?: boolean;
  command?: string;
  request_id?: string;
  message_type?: string;
  model_slug?: string;
  default_model_slug?: string;
  resolved_model_slug?: string;
  reasoning_status?: string;
  reasoning_start_time?: number;
  reasoning_end_time?: number;
  finish_details?: { type: string; stop_tokens: number[] };
  is_complete?: boolean;
  citations?: any[];
  content_references?: any[];
  code_blocks?: Record<string, { id: string; edited: boolean; previewable: boolean; preview_language: null }>;
  search_result_groups?: any[];
  search_model_queries?: { type: string; queries: string[] };
  can_save: boolean;
  dictation?: boolean;
  permissions?: Array<{ type: string; status: string; notification_channel_id: string; notification_channel_name: string; notification_priority: number }>;
}
